-- MySQL Script generated by MySQL Workbench
-- Tue Jul 30 11:58:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzaplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaplace` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzaplace` ;

-- -----------------------------------------------------
-- Table `pizzaplace`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`province` (
  `idProvince` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idProvince`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaplace`.`locality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`locality` (
  `idLocality` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `province` INT NOT NULL,
  PRIMARY KEY (`idLocality`),
  INDEX `province_idx` (`province` ASC) VISIBLE,
  CONSTRAINT `province`
    FOREIGN KEY (`province`)
    REFERENCES `pizzaplace`.`province` (`idProvince`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaplace`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`adress` (
  `idAdress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(4) NOT NULL,
  `floor` VARCHAR(3) NOT NULL,
  `door` VARCHAR(4) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `postal_code` VARCHAR(6) NOT NULL,
  `locality` INT NOT NULL,
  PRIMARY KEY (`idAdress`),
  INDEX `locality_idx` (`locality` ASC) VISIBLE,
  CONSTRAINT `locality`
    FOREIGN KEY (`locality`)
    REFERENCES `pizzaplace`.`locality` (`idLocality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaplace`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `adress` INT NOT NULL,
  `postal_code` VARCHAR(6) NOT NULL,
  `locality` INT NOT NULL,
  `province` INT NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `adress_idx` (`adress` ASC) VISIBLE,
  CONSTRAINT `adress`
    FOREIGN KEY (`adress`)
    REFERENCES `pizzaplace`.`adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaplace`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `adress` INT NOT NULL,
  PRIMARY KEY (`idStore`),
  INDEX `adress_idx` (`adress` ASC) VISIBLE,
  CONSTRAINT `adress`
    FOREIGN KEY (`adress`)
    REFERENCES `pizzaplace`.`adress` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaplace`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`employee` (
  `idEmployee` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` ENUM('COOK', 'DELIVERY') NOT NULL,
  `store` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `store_idx` (`store` ASC) VISIBLE,
  CONSTRAINT `store`
    FOREIGN KEY (`store`)
    REFERENCES `pizzaplace`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaplace`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `client` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `delivery` TINYINT NOT NULL,
  `quantityOfProducts` INT NOT NULL,
  `totalPrice` FLOAT NOT NULL,
  `store` INT NOT NULL,
  `deliveryPerson` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `client_idx` (`client` ASC) VISIBLE,
  INDEX `store_idx` (`store` ASC) VISIBLE,
  INDEX `delivery_person_idx` (`deliveryPerson` ASC) VISIBLE,
  CONSTRAINT `client`
    FOREIGN KEY (`client`)
    REFERENCES `pizzaplace`.`client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store`
    FOREIGN KEY (`store`)
    REFERENCES `pizzaplace`.`store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `delivery_person`
    FOREIGN KEY (`deliveryPerson`)
    REFERENCES `pizzaplace`.`employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaplace`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NULL,
  `image` BLOB NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaplace`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`pizza` (
  `idPizza` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPizza`),
  CONSTRAINT `idPizza`
    FOREIGN KEY (`idPizza`)
    REFERENCES `pizzaplace`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzaplace`.`order_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaplace`.`order_has_product` (
  `order_idOrder` INT NOT NULL,
  `product_idProduct` INT NOT NULL,
  PRIMARY KEY (`order_idOrder`, `product_idProduct`),
  INDEX `fk_order_has_product_product1_idx` (`product_idProduct` ASC) VISIBLE,
  INDEX `fk_order_has_product_order1_idx` (`order_idOrder` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_idOrder`)
    REFERENCES `pizzaplace`.`order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `pizzaplace`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
