db.NYRestaurants.find({})
db.NYRestaurants.find({},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0})
db.NYRestaurants.find({},{restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1, _id: 0})
db.NYRestaurants.find({"borough" : "Bronx"})
db.NYRestaurants.find({"borough" : "Bronx"}).limit(5)
db.NYRestaurants.find({"borough" : "Bronx"}).skip(5).limit(5)
db.NYRestaurants.find({"grades.score" : {$gt : 90}})
db.NYRestaurants.find({"grades.score" : ({$gt : 80}, {$lt : 100})})
db.NYRestaurants.find({"address.coord.0" : {$lt : -95.754168}})
db.NYRestaurants.find({"grades.score" : ({$gt : 80}, {$lt : 100})})
db.NYRestaurants.find({cuisine:{$ne:"American "},"grades.score":{$gt:70},"address.coord.0":{$lt:-65.754168}})
db.NYRestaurants.find({$and:[{cuisine:{$ne:"American "}}, {"grades.grade": "A"}, {borough:{$ne:"Brooklyn"}}]}).sort({cuisine:-1})
db.NYRestaurants.find({name: /^Wil/},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({name: /ces$/},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({name: /reg/i},{restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({$and:[{borough:"Bronx"}, {$or:[{cuisine: "American "}, {cuisine: "Chinese"}]}]})
db.NYRestaurants.find({borough:{$in:['Staten Island', 'Queens' , 'Bronx' , 'Brooklyn']}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({borough:{$nin:['Staten Island', 'Queens' , 'Bronx' , 'Brooklyn']}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({"grades.score": {$lt: 10}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({$or:[{cuisine: "Seafood"},{name: {$not:/^Wil/}}]}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
db.NYRestaurants.find({"grades":{$elemMatch: {"grade": "A", "score": 11, "date": ISODate("2014-08-11T00:00:00Z")}}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1})
db.NYRestaurants.find({"grades.1.grade": "A", "grades.1.score": 9, "grades.1.date": ISODate("2014-08-11T00:00:00Z")}, {restaurant_id: 1, name: 1, grades: 1, _id: 0})
db.NYRestaurants.find({"address.coord.1": {$gt: 42, $lte: 52}},{restaurant_id: 1, name: 1, address: 1, coord: 1, _id: 0})
db.NYRestaurants.find({}).sort({name: 1})
db.NYRestaurants.find({}).sort({name: -1})
db.NYRestaurants.find({}).sort({cuisine: 1, borough: -1})
db.NYRestaurants.find({'address.street': null })
db.NYRestaurants.find({"address.coord": {$type: "double"}})
db.NYRestaurants.find({"grades.score":{$mod:[7,0]}},{restaurant_id: 1, name: 1, grades : 1, _id:0})
db.NYRestaurants.find({name:/mon/i}, {name:1, borough:1, 'address.coord':1, cuisine:1, _id:0})
db.NYRestaurants.find({name:/^Mad/}, {name:1, borough:1, 'address.coord':1, cuisine:1, _id:0})